"""membuat tabel mahasiswa

Revision ID: 22125ae42720
Revises: bdd24954d650
Create Date: 2023-12-07 09:20:44.967986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22125ae42720'
down_revision = 'bdd24954d650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nim', sa.String(length=30), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('alamat', sa.String(length=255), nullable=False),
    sa.Column('dosen_satu', sa.BigInteger(), nullable=True),
    sa.Column('dosen_Dua', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['dosen_Dua'], ['dosen.id'], ),
    sa.ForeignKeyConstraint(['dosen_satu'], ['dosen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###
