"""make table gambar

Revision ID: 884087f40eff
Revises: a989391a3277
Create Date: 2023-12-18 10:09:36.720447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884087f40eff'
down_revision = 'a989391a3277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gambar',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gambar')
    # ### end Alembic commands ###
